# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0078_auto_20171024_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('storage_hash', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='sort order')),
                ('item_type', models.CharField(max_length=50)),
                ('message_type', models.CharField(max_length=50)),
                ('node_id', models.CharField(max_length=50)),
                ('actions', models.TextField(blank=True, default=b'{}')),
                ('is_supplementary', models.BooleanField(default=False)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_item', to='contentcuration.Story')),
            ],
        ),
    ]
