# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0079_story_storyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='contentcuration.Channel'),
        ),
    ]
