# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0080_story_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storage_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
