# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0081_auto_20180123_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyitem',
            name='message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='node_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
