# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0082_auto_20180123_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='actions',
            field=models.TextField(default=b'{}'),
        ),
    ]
