# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0084_auto_20180129_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
