# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0085_auto_20180129_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
